README.md, package-lock.json, package.json, src/MonacoJSONEditor.js
add vim mode command to command palette and remove existing vim keybind
add new command "replace meta schema" to allow testing alternate schemas
=> feat: add commands

src/MonacoJSONEditor.js
=> fix: vim mode affecting editor sizing

package-lock.json
=> fix: upgrade json markdown table

src/App.js
=> fix: enable html rendering option in markdown docs component

README.md
rel https://github.com/open-rpc/spec/issues/72
=> fix: OPEN-RPC -> OpenRPC

src/JSONValidationErrorList.js
=> fix: error messages too long

src/App.js, src/fetchSchemaFromRpcDiscover.js
=> fix: rpc.discover

src/App.js, src/Documentation.js, src/Errors/Errors.js, src/Errors/Errors.test.js, src/ExamplePairing/ExamplePairing.js, src/ExamplePairings/ExamplePairings.js, src/Methods/Methods.js
=> feat: add Error support

README.md
see https://github.com/open-rpc/spec/issues/72
=> fix: OpenRPC consistent as naming

package-lock.json, package.json, src/App.tsx, src/MonacoJSONEditor.tsx, tslint.json
fixes #86
fixes #76
**Screenshot**
`variables` functionality with no errors + tests passing:
=> fix: use meta-schema from npm

.circleci/config.yml, .releaserc, package-lock.json, package.json, src/App.tsx, src/AppBar/AppBar.tsx
=> fix: add gh pages release to semantic-release

.releaserc
=> fix: semantic releaserc

package.json
=> fix: add repository and bugs fields to package

README.md, bin/cli.js, bin/get-version.js, package-lock.json, package.json, src/App.tsx, src/AppBar/AppBar.tsx
fixes #114
fixes #113
fixes #45
fixes #43
=> fix: add cli

config/paths.js, package-lock.json, package.json, scripts/build.js
=> fix: bump docs-react and cname for build

.circleci/config.yml
As discussed earlier with the correct history 🔢 .
=> chore(ci): add forked PRs to ci #132

package-lock.json, package.json, src/App.tsx, src/MonacoJSONEditor.tsx, src/SnackBar/SnackBar.test.tsx, src/fetchUrlSchemaFile.tsx
=> fix: bump meta-schema + docs-react

.releaserc, package-lock.json
=> fix: semantic release to npm

README.md
=> fix(README): spec document links

src/AppBar/AppBar.tsx
=> fix: remove appbar shadow

package-lock.json, package.json, src/App.css, src/App.tsx, src/MonacoJSONEditor.tsx
=> fix: add split pane resizing

src/App.tsx
=> fix: dark and light mode on react json view

README.md, package-lock.json, package.json, src/App.tsx, src/AppBar/AppBar.test.tsx, src/AppBar/AppBar.tsx, src/SearchBar/SearchBar.test.tsx, src/SearchBar/SearchBar.tsx, src/UISchema.tsx, src/themes/openrpcTheme.ts
SearchBar will auto complete example urls and names for now, but could improve other things in the developer experience later.
and also `?uiSchema[appBar][ui:input]=false`
=> feat: add searchbar to playground

src/fetchSchemaFromRpcDiscover.tsx
=> fix: rpc.discover should return json

src/App.tsx
=> fix: set initial dark theme json view

package-lock.json, package.json
=> fix(inspector): update to error handling

src/App.tsx
=> fix: default to petstore

package-lock.json, package.json, src/plugins/InspectorPlugin.tsx
=> fix: inspector overflow

package-lock.json, package.json
=> fix: update docs-react json schema object style

package-lock.json, package.json, src/App.tsx, src/OpenRPCEditor.tsx
=> fix: error sizing + bump inspector

src/App.tsx
=> fix: docs scroll sizes

package-lock.json, src/App.tsx, src/AppBar/AppBar.tsx, src/ExampleDocumentsDropdown/ExampleDocumentsDropdown.tsx, src/hooks/useParsedSchema.tsx, src/stores/UISchemaStore.ts
- change examples dropdown to be with the `url input`
- change icons + text for fullscreen/edit/darkmode
=> fix: appbar ui fixes

src/App.tsx
=> fix: set dark mode via params

package-lock.json, package.json
=> fix: update @open-rpc/meta-schema to latest

package-lock.json, package.json
rel https://github.com/open-rpc/docs-react/pull/404
=> fix: add docs-react syntax highlighting
